# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/prarthanamahesh21-hub/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [5]:
import os
from google.colab import userdata
from datasets import load_dataset

HF_TOKEN = userdata.get("HF_TOKEN")

print("HF token loaded:", HF_TOKEN is not None)

HF token loaded: True

In [7]:
from datasets import load_dataset

dim_content = load_dataset(
    "FlyRank/internship-warehouse",
    "dim_content",
    token=HF_TOKEN
)

print(dim_content)

dim_content.parquet: reconstructing file:   0%|          |  0.00B / 19.6MB

dim_content.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/519606 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used', 'char_count', 'word_count', 'last_optimized_date', 'optimization_eligible_date', 'is_published', 'is_deleted'],
        num_rows: 519606
    })
})

In [8]:
fact_performance = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    token=HF_TOKEN
)

fact_query = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_query_90d",
    token=HF_TOKEN
)

print(fact_performance)
print(fact_query)

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

fact_content_query_90d.parquet: reconstructing file:   0%|          |  0.00B / 60.7MB

fact_content_query_90d.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2414248 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
        num_rows: 78835655
    })
})
DatasetDict({
    train: Dataset({
        features: ['client_hash_id', 'content_hash_id', 'query_hash_id', 'query_char_count', 'query_token_count', 'window_start', 'window_end', 'impressions_90d', 'clicks_90d', 'impressions_last30', 'clicks_last30', 'impressions_prev30', 'clicks_prev30', 'avg_position_90d', 'avg_position_last30', 'avg_position_prev30', 'content_total_impressions_90d', 'content_visible_query_count', 'rare_query_count', 'rare_impressions_share', 'anonymized_impressions_share'],
        num_rows: 2414248
    })
})

In [9]:
import pandas as pd
import duckdb

content = dim_content["train"]
performance = fact_performance["train"]
query_90d = fact_query["train"]

print("Content rows:", len(content))
print("Performance rows:", len(performance))
print("Query 90d rows:", len(query_90d))

Content rows: 519606
Performance rows: 78835655
Query 90d rows: 2414248

In [10]:
print(performance.cache_files)
print(query_90d.cache_files)
print(content.cache_files)

[{'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00000-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00001-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00002-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00003-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00004-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00005-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00006-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00007-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00008-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00009-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00010-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00011-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00012-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00013-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00014-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00015-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00016-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00017-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00018-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00019-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00020-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00021-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00022-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00023-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00024-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00025-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00026-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00027-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00028-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00029-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00030-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00031-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00032-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00033-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00034-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00035-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00036-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00037-of-00039.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_daily_performance/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00038-of-00039.arrow'}]
[{'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_query_90d/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00000-of-00002.arrow'}, {'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/fact_content_query_90d/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train-00001-of-00002.arrow'}]
[{'filename': '/root/.cache/huggingface/datasets/FlyRank___internship-warehouse/dim_content/0.0.0/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/internship-warehouse-train.arrow'}]

In [13]:
# Check the March 2026 performance slice without loading all 78M rows

march_performance = performance.filter(
    lambda row: str(row["report_date"])[:7] == "2026-03"
)

print("March 2026 rows:", len(march_performance))

Filter:   0%|          | 0/78835655 [00:00<?, ? examples/s]

March 2026 rows: 9841378

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [16]:
HF_TOKEN
dim_content
fact_performance
fact_query
content
performance
query_90d

Dataset({
    features: ['client_hash_id', 'content_hash_id', 'query_hash_id', 'query_char_count', 'query_token_count', 'window_start', 'window_end', 'impressions_90d', 'clicks_90d', 'impressions_last30', 'clicks_last30', 'impressions_prev30', 'clicks_prev30', 'avg_position_90d', 'avg_position_last30', 'avg_position_prev30', 'content_total_impressions_90d', 'content_visible_query_count', 'rare_query_count', 'rare_impressions_share', 'anonymized_impressions_share'],
    num_rows: 2414248
})

In [17]:
print("Development month: March 2026")
print("Expected date window: 2026-03-01 to 2026-03-31")
print("March rows:", len(march_performance))

Development month: March 2026
Expected date window: 2026-03-01 to 2026-03-31
March rows: 9841378

In [18]:
print(type(performance))
print(type(content))
print(type(query_90d))

<class 'datasets.arrow_dataset.Dataset'>
<class 'datasets.arrow_dataset.Dataset'>
<class 'datasets.arrow_dataset.Dataset'>

In [19]:
import duckdb

con = duckdb.connect()

con.register("dim_content", content._data.table)
con.register("fact_content_daily_performance", performance._data.table)
con.register("fact_content_query_90d", query_90d._data.table)

print("DuckDB setup complete")

DuckDB setup complete

In [20]:
grain_check = con.sql("""
SELECT
    COUNT(*) AS march_rows,
    COUNT(DISTINCT content_hash_id || '|' || CAST(report_date AS VARCHAR)) AS unique_page_day_pairs,
    COUNT(*) -
        COUNT(DISTINCT content_hash_id || '|' || CAST(report_date AS VARCHAR))
        AS duplicate_page_day_rows
FROM fact_content_daily_performance
WHERE report_date >= DATE '2026-03-01'
  AND report_date < DATE '2026-04-01'
""").df()

grain_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   march_rows  unique_page_day_pairs  duplicate_page_day_rows
0     9841378                9841378                        0

In [21]:
march_window = con.sql("""
SELECT
    COUNT(*) AS march_rows,
    MIN(report_date) AS first_report_date,
    MAX(report_date) AS last_report_date
FROM fact_content_daily_performance
WHERE report_date >= DATE '2026-03-01'
  AND report_date < DATE '2026-04-01'
""").df()

march_window

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   march_rows first_report_date last_report_date
0     9841378        2026-03-01       2026-03-31

In [22]:
availability_check = con.sql("""
SELECT
    COUNT(*) AS march_rows,
    COUNT(*) FILTER (WHERE gsc_data_available IS TRUE) AS gsc_available_rows,
    COUNT(*) FILTER (WHERE gsc_data_available IS NOT TRUE) AS gsc_not_available_rows
FROM fact_content_daily_performance
WHERE report_date >= DATE '2026-03-01'
  AND report_date < DATE '2026-04-01'
""").df()

availability_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   march_rows  gsc_available_rows  gsc_not_available_rows
0     9841378             3611061                 6230317

In [1]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

One row = one content page for the selected monthly snapshot. I will develop and verify the contract on March 2026 data. The goal is to rank pages for possible content-refresh review using information available at the decision moment.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

Feature: content_age_days, word_count, impressions_90d, clicks_90d, and pageviews_90d. These are historical or page-level signals that can be known when the page is being considered for review.

Label: A future-performance outcome used only to evaluate whether a page should have been prioritized. It is not used as an input feature.

Context: content_id, client_id, content_type, and other identifying/context fields needed to group or describe pages.

Excluded: Any future-performance field or field calculated from the outcome window is excluded from the feature set because it would not be known at the decision moment and would cause leakage.

In [2]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

In [23]:
con.sql("""
SELECT *
FROM fact_content_query_90d
LIMIT 5
""").df()

,client_hash_id,content_hash_id,query_hash_id,query_char_count,query_token_count,window_start,window_end,impressions_90d,clicks_90d,impressions_last30,...,impressions_prev30,clicks_prev30,avg_position_90d,avg_position_last30,avg_position_prev30,content_total_impressions_90d,content_visible_query_count,rare_query_count,rare_impressions_share,anonymized_impressions_share
0,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_58b1b001f839d699,17,3,2026-04-02,2026-06-30,11,0,0,...,11,0,10.818182,NaN,10.818182,1466,14,32,0.043656,0.725102
1,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_922b8eca2a24cd34,34,7,2026-04-02,2026-06-30,13,0,0,...,1,0,1.769231,NaN,11.000000,1466,14,32,0.043656,0.725102
2,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_9f0c36a6ae2a6a99,16,2,2026-04-02,2026-06-30,16,0,11,...,5,0,23.562500,24.272727,22.000000,1466,14,32,0.043656,0.725102
3,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_a032820b5467e996,24,4,2026-04-02,2026-06-30,55,0,1,...,1,0,2.200000,13.000000,0.000000,1466,14,32,0.043656,0.725102
4,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_ba1a2f131961c5da,18,3,2026-04-02,2026-06-30,14,0,0,...,0,0,3.428571,NaN,NaN,1466,14,32,0.043656,0.725102

In [24]:
con.sql("""
SELECT *
FROM dim_content
LIMIT 5
""").df()

,client_hash_id,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,...,category_count,keyword_created_date,provider_used,model_used,char_count,word_count,last_optimized_date,optimization_eligible_date,is_published,is_deleted
0,client_04660893ae39614a,content_004de9653278b5a4,keyword_e754999ab88dd9f2,url_d6091f18cf628794,22,4,108,2026-05-30,2026-07-01,keyword article,...,3,2026-05-12,gemini-generate-content,gemini-3-flash-preview,15682,2555,NaT,NaT,True,False
1,client_04660893ae39614a,content_00dc5efae381b2ab,keyword_4329d7aede8e208b,url_3a66d2f2e36823ca,31,6,95,2026-06-12,2026-07-01,keyword article,...,4,2026-06-01,gemini-generate-content,gemini-3-flash-preview,15438,2430,NaT,NaT,True,False
2,client_04660893ae39614a,content_01410f2556c327ac,keyword_9b08047d3d2a0406,url_809eda7a7e20b3b2,22,5,82,2026-05-09,2026-07-01,keyword article,...,4,2026-05-06,gemini-generate-content,gemini-3-flash-preview,16576,2645,NaT,NaT,True,False
3,client_04660893ae39614a,content_019f27f634053ca7,keyword_e7cec7ab1804c1c2,url_5fb42bafc4399861,14,3,92,2026-06-15,2026-06-15,keyword article,...,4,2026-06-01,gemini-generate-content,gemini-3-flash-preview,15457,2522,NaT,NaT,True,False
4,client_04660893ae39614a,content_01efa71faea45dcc,keyword_56b0062a1d8b7524,url_ece0abc3e5fb75f9,24,6,98,2026-05-21,2026-06-01,keyword article,...,4,2026-05-12,gemini-generate-content,gemini-3-flash-preview,15776,2552,NaT,NaT,True,False

In [26]:
features_march = con.sql("""
WITH performance_90d AS (
    SELECT
        content_hash_id,

        SUM(
            CASE
                WHEN gsc_data_available IS TRUE
                THEN COALESCE(gsc_impressions, 0)
                ELSE 0
            END
        ) AS gsc_impressions_90d,

        SUM(
            CASE
                WHEN gsc_data_available IS TRUE
                THEN COALESCE(gsc_clicks, 0)
                ELSE 0
            END
        ) AS gsc_clicks_90d,

        SUM(
            CASE
                WHEN ga4_data_available IS TRUE
                THEN COALESCE(ga4_pageviews, 0)
                ELSE 0
            END
        ) AS ga4_pageviews_90d

    FROM fact_content_daily_performance

    WHERE report_date >= DATE '2025-12-01'
      AND report_date < DATE '2026-03-01'

    GROUP BY content_hash_id
)

SELECT
    c.content_hash_id,

    DATE_DIFF(
        'day',
        CAST(c.content_created_date AS DATE),
        DATE '2026-03-01'
    ) AS content_age_days,

    c.word_count,
    p.gsc_impressions_90d,
    p.gsc_clicks_90d,
    p.ga4_pageviews_90d

FROM dim_content c

LEFT JOIN performance_90d p
    ON c.content_hash_id = p.content_hash_id

WHERE c.content_created_date < DATE '2026-03-01'
  AND c.is_published IS TRUE
  AND c.is_deleted IS FALSE
""").df()

print("Feature frame shape:", features_march.shape)
features_march.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Feature frame shape: (303321, 6)

,content_hash_id,content_age_days,word_count,gsc_impressions_90d,gsc_clicks_90d,ga4_pageviews_90d
0,content_8aaf77f1ef9c7e0e,145,3161,0.0,0.0,0.0
1,content_8ad59837fbe49ad9,145,2982,0.0,0.0,0.0
2,content_8cbbd525075c3197,145,3565,0.0,0.0,0.0
3,content_8e12c0ced144f028,145,3357,0.0,0.0,0.0
4,content_8f4ecf030ca35fb9,145,3014,23.0,0.0,0.0

In [27]:
# Future outcome: April 2026 GSC clicks

future_label = con.sql("""
SELECT
    content_hash_id,
    SUM(
        CASE
            WHEN gsc_data_available IS TRUE
            THEN COALESCE(gsc_clicks, 0)
            ELSE 0
        END
    ) AS future_gsc_clicks
FROM fact_content_daily_performance
WHERE report_date >= DATE '2026-04-01'
  AND report_date < DATE '2026-05-01'
GROUP BY content_hash_id
""").df()

future_label["label"] = (
    future_label["future_gsc_clicks"] > 0
).astype(int)

model_df = features_march.merge(
    future_label[["content_hash_id", "label"]],
    on="content_hash_id",
    how="inner"
)

print("Model frame shape:", model_df.shape)
print("Positive labels:", model_df["label"].sum())
print("Negative labels:", (model_df["label"] == 0).sum())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Model frame shape: (293504, 7)
Positive labels: 53259
Negative labels: 240245

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

Grain — does one row really correspond to the unit you claimed?
March slice — how many rows are there and what is the date/window range?
Availability/missingness — use the required IS TRUE condition.

In [3]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

In [4]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

Limitation: This data supports directional, decision-support ranking, but it cannot tell us whether a content team would actually choose to refresh a page. Historical coverage is also not equally complete for every page, and overlapping 90-day windows mean nearby monthly observations are not independent.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.